// <auto-generated />
namespace CoderCampsCRM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Changing_Company2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Changing_Company2));
        
        string IMigrationMetadata.Id
        {
            get { return "201602122057268_Changing_Company2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
